### ISSUE TITLE
structs.Map return empty map

### ISSUE THREAD

**Issue by hawkli-1994** [fatih/structs#112]
test := &commonlyUsedRedisTable{protocol: "test", status: "test"}
	m := structs.Map(test)
	fmt.Println(m)

       print: map[]

**Comment by mkrull** [comment]
The first example shows unexported fields are not included in the map.

**Comment by theblueskies** [comment]
Close this issue?

**Comment by fatih** [comment]
Hi,

Unfortunately, I'm archiving this project and will no longer maintaining it. For more information, please read my blog post: [Taking an indefinite sabbatical from my projects.](https://arslan.io/2018/10/09/taking-an-indefinite-sabbatical-from-my-projects/)

Thanks for the feedback and contribution.
