### ISSUE TITLE
creating an exported field

### ISSUE THREAD

**Issue by BEZEI2K** [fatih/structs#23]
Is it possible to create a field if it is unsettable?

**Comment by fatih** [comment]
Can you give more detail ? You can only create fields when you define a struct. After that it's not possible anymore.

**Comment by BEZEI2K** [comment]
Ok, What I needed to be able to do is loop over two data structs. Compare one against other, and where different update. So if Struct1 has a field Struct2 doesn't, we create the field and assign a value.

**Comment by fatih** [comment]
Nope this is not possible. Structs are types that needs to be declared during compile time and can't be set in runtime.
