### ISSUE TITLE
add options to use custom struct tag name instead of `structs:"..."`

### ISSUE THREAD

**Issue by oryband** [fatih/structs#25]
I would like to use `json:"..."` instead of `structs:".."`, for now I am forced to use both when a struct is used by `encoding/json` and `fatih/structs` with converting structs to `map[string]interface{}`.
```go
type ErrorResponse struct {
	Error string `json:"error" structs:"error"`
}
```

**Comment by oryband** [comment]
Specifically, I need this in the `structs.Map()` function, but I guess it would be good if this would be added as to other places in the code as well.

**Comment by fatih** [comment]
Actually you can do it already http://godoc.org/github.com/fatih/structs#Struct :) By default it's "structs" but you can change it to "json".

**Comment by fatih** [comment]
Change the TagnName field.

**Comment by fatih** [comment]
Or change the global variable name "DefaultTagName"

**Comment by oryband** [comment]
@fatih hey cool! thanks. you're quick :)

**Comment by fatih** [comment]
You're welcome :)
