### ISSUE TITLE
Can it work when fields start with an lowercase

### ISSUE THREAD

**Issue by lionelmessi** [fatih/structs#43]
I tried using lowercase fields with 	

type photoUploadForm struct {
	userid    string `form:"userid" valid:"Required"`
	caption   string `form:"caption" valid:"Required"`
}

m := structs.Map(ph)

m is always empty.

**Comment by lionelmessi** [comment]
ok we need to use name in struct!

**Comment by tab1293** [comment]
@lionelmessi what was the solution to this issue? Is it possible to use lowercase properties in the struct definition?
