### ISSUE TITLE
Why structs.Map() convert anonymous field in sub map?

### ISSUE THREAD

**Issue by n3wtron** [fatih/structs#45]
```
type A{
  Name string
}

type B{
 A
 Surname string
}
var t B;
structs.Map(t)
```
generate a map like
`map[A:map[Name:] Surname:]`
but A is an anonymous field I'm expecting a flat map like
`map[Name:Surname:]`

**Comment by n3wtron** [comment]
I did this modification https://github.com/n3wtron/structs/commit/2c35fa8e22ce37fce36cc6f749cb812b1138d44c
I don't know if its correct

**Comment by fatih** [comment]
Hi @n3wtron. It's not allowed because the struct A and B might have the same struct names and it would collide. It's not a bug, it's a design decision.

**Comment by n3wtron** [comment]
Hi @fatih thank you for the answer.
What do you think about using a tag to choose if convert a nested struct in a nested map?
If you have some time could you take a look https://github.com/n3wtron/structs/commit/d97a96e28c0bd5866c42f0d71dafb0f44893585c 

Have a nice day

**Comment by fatih** [comment]
Hi @n3wtron I think open a PR to the repo with these changes and discuss it there. Also what about duplicate fields? I think if you make it explicit that it will be overwritten I think we might introduce it.

**Comment by n3wtron** [comment]
Hi @fatih, I will open a PR, but first I'll have to add a test on structs_test.go.
I can't duplicate fields, because the structure that I'm trying to map is come from an other library.

Thank you.
