### ISSUE TITLE
Global omitempty?

### ISSUE THREAD

**Issue by ak2344** [fatih/structs#54]
Thanks for creating this package, it's super simple and useful.

Do you know if it's possible to request an omitempty policy at a global / struct level without having to specify it for every field?

Thanks!

**Comment by fatih** [comment]
Hi @ak2344 

Unfortunately there is no such feature. Think of it's like how `encoding/json` and others does it. They also don't provide any global flags. I'm not thinking to add something because there is little we can win from this. Thanks!
