### ISSUE TITLE
Nested array structs dont pick up custom tags

### ISSUE THREAD

**Issue by shardnit** [fatih/structs#58]
Consider following example where struct person consists of array of addresses:

```go

package main

import (
	"fmt"

	"github.com/fatih/structs"
)

func main() {
	type address struct {
		Country string `structs:"country"`
	}

	type person struct {
		Name      string    `structs:"name"`
		Addresses []address `structs:"addresses"`
	}

	p := person{Name: "test", Addresses: []address{address{Country: "England"}}}
	fmt.Printf("%+v", structs.Map(p))
}
```

The output is (custom tag for country is not picked):
`map[name:test addresses:[{Country:England}]]`

while the expected output is:
`map[name:test addresses:[{country:England}]]`

**Comment by fatih** [comment]
Thanks @shardnit 

I'll take a look soon at it. My macbook was broken and I didn't had the time to look at it.

**Comment by n3wtron** [comment]
I think that the correct output should be 
map[name:test addresses:[map[country:England]]]

**Comment by fatih** [comment]
@shardnit checkout please https://github.com/fatih/structs/pull/60, it solves your problem.
