### ISSUE TITLE
Invalid Type

### ISSUE THREAD

**Issue by RongxinZhang** [fatih/structs#65]
Hi @fatih 

I have a struct like this:

``` js
type RStruct struct {
    Items []struct {
        Percentage  int         `json:"percentage"`
        Host             string      `json:"host"`
        Indices          interface{} `json:"indices"`
        IP               []string    `json:"ip"`
    } `json:"items"`
}
```

However, when I try to convert the returned the return object, I get an error:

![screen shot 2016-06-27 at 11 14 01 am](https://cloud.githubusercontent.com/assets/3782456/16390597/69d8a690-3c58-11e6-9ebf-7a1015570094.png)

Any thoughts?

**Comment by RongxinZhang** [comment]
Seems to be related to this: https://github.com/pquerna/ffjson/issues/27

**Comment by fatih** [comment]
Hi @RongxinZhang Can you please provide a reproducible `main.go` file? What do you mean by `when I try to convert the returned the return object` ? Which function did you use?

**Comment by fatih** [comment]
Closing as I didn't get any response per months. Feel free to open again.
