### ISSUE TITLE
golang 1.7 issue

### ISSUE THREAD

**Issue by client9** [fatih/structs#72]
Here for tracking.  Something in koding/multiconfig is panic-ing.

via koding/multiconfig#50

"""
It's issue with http://github.com/fatih/structs, the check for IsExported should be adapted as described in golang/go#12367
"""

which says

```
Code that assumes

f.PkgPath != nil 
means a field is unexported and must be ignored must now be revised to check for

f.PkgPath != nil && !f.Anonymous
for it to walk into the embedded structs to look for exported fields contained within.
```

**Comment by fatih** [comment]
This is issue is not related to `structs` (https://github.com/koding/multiconfig/issues/50#issuecomment-246335494). Thanks.
