### ISSUE TITLE
data type limitation

### ISSUE THREAD

**Issue by rajeshneo** [fatih/structs#74]
Is there a limitation that this package only work on int value. I tried with int64/uint/uint64 and somehow it does not seems to change values

Ref:
package main

import (
	"fmt"

	"github.com/fatih/structs"
)

type Data struct {
	IntVal    uint64
	StringVal string
	NewStruct NewStruct
}

type NewStruct struct {
	InVal int
}

func main() {
	var vals Data
	vals.IntVal = 1
	vals.NewStruct.InVal = 1
	vals.StringVal = "Hello"
	fmt.Println("Values are", vals)
	s := structs.New(&vals)
	//t := s.Field("IntVal")
	//fmt.Printf("Type of %s is %s\n", "IntVal", t.Kind())
	//	s.Field("StringVal").Set("Nopes")
	s.Field("IntVal").Set(2)
	s.Field("NewStruct").Field("InVal").Set(2)
	fmt.Println("New Values are", vals)
	//doIt(&vals)
	//fmt.Println("New Values after doIt", vals)
	return
}

Output:
Values are {1 Hello {1}}
New Values are {1 Hello {2}}

**Comment by rajeshneo** [comment]
ok found the issue with my code.. i was trying to assign 2 to uint64 value..it was considering 2 as int and was throwing a error.. it would be nice if can find a way to somehow overcome this casting need.

**Comment by fatih** [comment]
Closing this issue as it's not readable. Please feel free to open another one with more detailed information.
