### ISSUE TITLE
Is there a way to do a non recursive nested struct map conversion?

### ISSUE THREAD

**Issue by ryanstinson** [fatih/structs#79]
I have some fields within my stuct that use null.String types which are structs themselves. However, these are wrappers for scalar types so I don't want to create nested maps for these. Is there an option to turn off recursive map conversion?

**Comment by fatih** [comment]
Yes there is. Use the `omitnested` tag option. There is also an example in the docs. Thanks

**Comment by ryanstinson** [comment]
Thank you!


________________________________
