### ISSUE TITLE
Cannot flatten the nested struct.

### ISSUE THREAD

**Issue by peter-hon** [fatih/structs#82]
When I use flatten, 
          `type Message struct {
	   Model `structs:",flatten"`	   
           Name `structs:"name"`
        }` 

      `type Model struct {
	CreatedAt rdb.Timestamp ` structs:"created_at"`
	UpdatedAt rdb.Timestamp `structs:"updated_at"`
      }`

message is the instance of Message
when I use structs.Map(message)

It always return map[string]interface{} contains map[string]interface{} of Model. Seems Model fields cannot be flatten to same level of Name. Something wrong with my code?

**Comment by fatih** [comment]
@peter-hon Can you please give a reproducible case so I can test it. Your example is not easy on the eyes and can't be read. Thanks

**Comment by peter-hon** [comment]
Thanks Faith, the reason I can't use 'flatten' is because I did not get the latest structs. I update it and it works
