### ISSUE TITLE
Any way to override field names when converting a struct to a map?

### ISSUE THREAD

**Issue by TheChuckster** [fatih/structs#83]
JSON has the following:

```
type ErrorResponse struct {
	ErrorCode int    `json:"error_code"`
	ErrorStr  string `json:"error_str"`
}
```

which is a bit friendlier (BUT not Go style)...

**Comment by fatih** [comment]
Yes, use `structs` in addition to `json`. Checkout the docs for more info: https://godoc.org/github.com/fatih/structs#example-Map--Tags

**Comment by chuckhacker** [comment]
Thanks @fatih !
