### ISSUE TITLE
Versions and tags 

### ISSUE THREAD

**Issue by henti** [fatih/structs#84]
Hi there, 

I'm busy packaging structs for Debian as a dependency for minio. For packaging to work correctly, we need to be able to scan for updated versions, and for that we need releases or tags. Please read https://wiki.debian.org/debian/watch and specifically https://wiki.debian.org/debian/watch#GitHub for more information on tags/release information in github that is needed to make packaging easier. 

Can you please tag or release your software accordingly. 

Regards
Henti

**Comment by fatih** [comment]
Hi @henti 

I've released it with `v1.0.0`. https://github.com/fatih/structs/releases/tag/v1.0.0 

Thanks for the notice

**Comment by henti** [comment]
Thanks @fatih 

For you to track. 

https://mentors.debian.net/package/golang-github-fatih-structs

H

**Comment by henti** [comment]
@fatih Thought you'd want to know.

https://packages.debian.org/sid/devel/golang-github-fatih-structs-dev

**Comment by fatih** [comment]
Thanks @henti for the update 👍
