### ISSUE TITLE
Get tag-value without omitempty

### ISSUE THREAD

**Issue by rogierlommers** [fatih/structs#91]
Excellent package! One question though: I sometimes need to get the tag() from a struct value, but then without the "omitempty" part. Does it make sense to create a dedicated method for that? So instead of `func (f *Field) Tag(key string) string` to have something like `func (f *Field) TagWithoutOmitEmpty(key string) string`?

**Comment by fatih** [comment]
Hi @rogierlommers 

Tags have their own syntax. I recommend you get them via `Tag()` and then the structtag package that allows you to do anything with that struct tag: https://github.com/fatih/structtag Thanks!

**Comment by rogierlommers** [comment]
👍 Didn't see that one :). Thanks!
